#!/bin/bash

HMAC-SHA256s(){
 KEY="${1}"
 DATA="${2}"
 shift 2
 printf "${DATA}" | openssl dgst -binary -sha256 -hmac "${KEY}" | od -An -vtx1 | sed 's/[ \n]//g' | sed 'N;s/\n//'
}

HMAC-SHA256h(){
 KEY="${1}"
 DATA="${2}"
 shift 2
 printf "${DATA}" | openssl dgst -binary -sha256 -mac HMAC -macopt "hexkey:${KEY}" | od -An -vtx1 | sed 's/[ \n]//g' | sed 'N;s/\n//'
}

AWS_ACCESS_KEY="${1}"
AWS_SECRET_KEY="${2}"
BUCKET="$(printf ${3} | awk 'BEGIN{FS="@"}{print $1}')"
REQUEST_REGION="$(printf $3 | awk 'BEGIN{FS="@"}{print ($2==""?"eu-central-1":$2)}')"
FILE_TO_UPLOAD="$4"
TARGET_FILE=$(echo -n "$5" | sed "s/\/$/\/$(basename ${FILE_TO_UPLOAD})/")

REQUEST_TIME="$(date +"%Y%m%dT%H%M%SZ")"
REQUEST_SERVICE="s3"
REQUEST_DATE="$(printf "${REQUEST_TIME}" | cut -c 1-8)"
AWS4SECRET="AWS4"${AWS_SECRET_KEY}
ALGORITHM="AWS4-HMAC-SHA256"
EXPIRE="$(if ! date -v+1d +%Y-%m-%d 2>/dev/null; then date -d tomorrow +%Y-%m-%d; fi)T12:00:00.000Z"
ACL="private"

POST_POLICY='{"expiration":"'${EXPIRE}'","conditions": [{"bucket":"'${BUCKET}'" },{"acl":"'${ACL}'" },["starts-with", "$key", "'${TARGET_FILE}'"],["eq", "$Content-Type", "application/octet-stream"],{"x-amz-credential":"'${AWS_ACCESS_KEY}'/'${REQUEST_DATE}'/'${REQUEST_REGION}'/'${REQUEST_SERVICE}'/aws4_request"},{"x-amz-algorithm":"'${ALGORITHM}'"},{"x-amz-date":"'${REQUEST_TIME}'"}]}'

UPLOAD_REQUEST=$(printf "${POST_POLICY}" | openssl base64 )
UPLOAD_REQUEST=$(echo -en ${UPLOAD_REQUEST} | sed "s/ //g")

SIGNATURE="$(HMAC-SHA256h $(HMAC-SHA256h $(HMAC-SHA256h $(HMAC-SHA256h $(HMAC-SHA256s ${AWS4SECRET} ${REQUEST_DATE} ) ${REQUEST_REGION}) ${REQUEST_SERVICE}) "aws4_request") ${UPLOAD_REQUEST})"

curl --silent \
	-F "key="${TARGET_FILE}"" \
	-F "acl="${ACL}"" \
	-F "Content-Type="application/octet-stream"" \
	-F "x-amz-algorithm="${ALGORITHM}"" \
	-F "x-amz-credential="${AWS_ACCESS_KEY}/${REQUEST_DATE}/${REQUEST_REGION}/${REQUEST_SERVICE}/aws4_request"" \
	-F "x-amz-date="${REQUEST_TIME}"" \
	-F "Policy="${UPLOAD_REQUEST}"" \
	-F "X-Amz-Signature="${SIGNATURE}"" \
	-F "file=@"${FILE_TO_UPLOAD} https://s3.${REQUEST_REGION}.amazonaws.com/${BUCKET}/ | cat
